# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  system.debug: true

steps:
- script: |
    cd src/net_core/ponos
    dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: 'src/net_core/ponos/Ponos.API.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore -o $(Build.ArtifactStagingDirectory)/API_$(Build.BuildNumber)'
    modifyOutputPath: false
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts Windows"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/API_$(Build.BuildNumber)'
    ArtifactName: 'ponos_service'
    publishLocation: 'Container'
